input_spike_train:

  dt: 0.1 # step time in ms
  offset_val: 3153
  t_ref: 2.0 # Absolute refractory periods (ms)
  t_ref_rel: 10.0 # Relative refractory periods (ms)
  rec: 2.0 # Sharpness of relative refractory function.
  scale_factor: 1.0
  refrac: 1.0
  